# Generated by Django 3.1.3 on 2020-11-15 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=1, height_field=360, upload_to='', width_field=250),
            preserve_default=False,
        ),
    ]
